### ISSUE TITLE
How to use IPFS check with a local IPFS node

### ISSUE THREAD

**Issue by momack2** [aschmahmann/ipfs-check#9]
It would be useful if [IPFS Check](https://ipfs-check.on.fleek.co) had some instructions and a link to a docs page about how to find your multiadder via the webUI as an individual running a local IPFS node (ex via IPFS Desktop).

## How to:
1. Open IPFS WebUI "Status" page via IPFS Desktop drop down or by visiting "http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/" (with default config settings)
2. Click the "Advanced" drop down to see more detailed node settings
3. Choose the top entry in your list of "Addresses" (these are the various multiaddrs via which your node is addressable)
4. Insert this address into the "multiaddr" text box

**Comment by aschmahmann** [comment]
Agreed some instructions are needed here. Although choosing which multiaddress address to use is non-obvious for people who aren't familiar with networking things (e.g. that 10.*, 192.168.*, 127.0.0.1, ::, ... are all local addresses).

This would likely be made easier if users were allowed to just put in their peerIDs instead of their full multiaddrs. It would be less precise at debugging, but users could fallback to querying particular multiaddresses if they wanted to. It does require some additional logic to implement though.

**Comment by aschmahmann** [comment]
@momack2 documenting how to use things currently is at #11.
